### ISSUE TITLE
Publish on Vison Pro

### ISSUE THREAD

**Issue by Aresnan** [ninjamode/Unity-VR-Gaussian-Splatting#10]
Hello, it's my pleasure to use you project for learning. Recently, I check your  repo to build a demo, which is by using unity platform to publish a vp project for the renderering effect of 3dgs, but unfortunately, it's not work at all, btw, my unity version is unity 6.28.
Quite bother me is that your demo scene which contains a physical body worked(just render a black block), but when I use your demo scene just replace the ply model is failure. I have no idea about this issue, so I have to beg you for helping. Could you give me some inspiration or some paradigm to copy. Further more , nothing could be better than if you contact me or give me a connect way, I'm looking forward it.

**Comment by ninjamode** [comment]
Vision Pro is not supported as of now. You can track this issue https://github.com/aras-p/UnityGaussianSplatting/issues/17 , as that would probably be the place where such support would land. I currently do not plan any active development of this repository, and the VR support in developed in here has been merge into the linked project.

**Comment by Aresnan** [comment]
Could you give me your email or any other contact Information.
