### ISSUE TITLE
Runtime Gaussian Editing

### ISSUE THREAD

**Issue by KEVIN09876** [ninjamode/Unity-VR-Gaussian-Splatting#4]
Hi,
Thank you for sharing this project. I have a question regarding the runtime.

Is there a way to modify the mean position values of individual Gaussians at runtime?
or any other gaussian features like RGB values, rotations ?

**Comment by ninjamode** [comment]
Yes, you can adjust these these parameters if you feel like it. There is, however, no specific API to do so; you would have to adjust some of the rendering code.

https://github.com/ninjamode/Unity-VR-Gaussian-Splatting/blob/599aa75ab713b797b7531db96f9f15c0bff298c6/package/Runtime/GaussianSplatRenderer.cs#L270

GaussianSplatRenderer.cs is the file where this data is set and where you could make adjustments. Or in the shader.

Note that this repository is a fork of https://github.com/aras-p/UnityGaussianSplatting to add vr support. As this is not VR related, you could also check there.
