### ISSUE TITLE
Gaussian Index different from the original model

### ISSUE THREAD

**Issue by KEVIN09876** [ninjamode/Unity-VR-Gaussian-Splatting#6]
Hello,

It seems that the Gaussian indexing in the Gaussian asset created in Unity is different from the original PyTorch model. I suspect this might be due to reordering in Morton order when the asset was created. Is there a simple way to disable this feature, assuming cutout is not being used?

Thank you! :)

**Comment by ninjamode** [comment]
Yes, the indices are reordered. As far as i know there is no easy way to disable this behavior. You could disable morton reordering in the asset creation, and change the morton decoding to return as is I guess? A quick search of the project does not yield that many locations where this would need to be done.
