### ISSUE TITLE
Settings for Quest

### ISSUE THREAD

**Issue by pablodawson** [ninjamode/Unity-VR-Gaussian-Splatting#7]
Hey! thanks for sharing your work.
You mention "Quest 3 gets 72 fps stable until around 400k Gaussians with proper settings". Would you be able to share what those settings are? Is that "Standalone Performant Preset" or anything else I'm missing?

**Comment by ninjamode** [comment]
Mainly make sure you enable center eye sorting and tune sort frequency for how much movement happens in your scene. Also make sure you don't place splats too close to the camera and try to reduce overdraw where possible

**Comment by pablodawson** [comment]
Thanks!
