### ISSUE TITLE
How can I duplicate gaussian objects with single rendering and shared resources?

### ISSUE THREAD

**Issue by KEVIN09876** [ninjamode/Unity-VR-Gaussian-Splatting#9]
Hello
I want to duplicate multiple objects with same gaussian models. Each have same textures.
Is it possible to share computation results ? and just instantiate gaussian objects?

**Comment by ninjamode** [comment]
The created asset can be shared. There is no way as of now to hold the data in memory only once but render it twice, saving memory. The computation cost will be incurred twice in any case, as sorting and rendering are position dependent (and each  gaussian is already instantiated).
